config/routes.rb
Trackrecord::Application.routes.draw do

  # Map root to the User account home page. The "root" mapping is so that
  # "root_url" exists, since the open_id_authentication plugin requires it.

  match '/' => 'users#home'
  match '/' => 'users#home', :as => :home

  # Mapping for the OpenID login system. The signin and signout
  # entries are for more readable paths in views; they're just
  # aliases for 'new' and 'destroy' actions.

  get '/session' => 'sessions#create', :as  => :open_id_complete

  resource :session

  match '/signin'  => 'sessions#new',     :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout

  # Allow in-progress account signup to be cancelled

  match '/users/cancel/:id' => 'users#cancel', :as => :user_cancel

  # Get common named routes for our resources. Don't be confused by the rather
  # esoteric use of Ruby block syntax here - this is just defining some nested
  # routes; e.g. customers have many tasks, so tasks are defined as resources
  # within customers. The longhand equivalent would be:
  #
  #   resources :customers do
  #     resources :tasks
  #   end
  #
  # ...and the Rails 2 equivalent used to be:
  #
  #  map.resources :customers, :has_many => [ :tasks ]

  resources( :customers      ) { resources :tasks                            }
  resources( :projects       ) { resources :tasks                            }
  resources( :control_panels ) { resources :tasks                            }
  resources( :tasks          ) { resources :users; resources :timesheet_rows }
  resources( :timesheets     ) { resources :timesheet_rows                   }

  resources( :users ) do
    resources :tasks
    resources :timesheets

    resources :saved_reports do
      get 'delete', :on => :member

      # This route is rather confusing and was determined by trial and error.
      # The intention is to get a variant of "new" which takes an ID, for the
      # "copy a report" case. The below achieves it (see "rake routes" and
      # look for "saved_reports#new" - it appears twice in different forms).
      # It also creates "user_saved_report_copy_<foo>()" methods.

      get 'new', :to => 'saved_reports#new', :as => 'copy'
    end

    resource :saved_reports_by_task,     :controller => :saved_reports_by_task,     :only => :create
    resource :saved_reports_by_project,  :controller => :saved_reports_by_project,  :only => :create
    resource :saved_reports_by_customer, :controller => :saved_reports_by_customer, :only => :create
    resource :saved_reports_by_user,     :controller => :saved_reports_by_user,     :only => :create
  end

  resources :audits
  resources :reports
  resources :charts
  resource  :task_imports
  resources :trees

  resources :help

  resource  :saved_report_auto_title, :only => :show
  resource  :timesheet_force_commit,  :only => [ :new, :create ]

  # Finally, the normal default rules at lowest priority

  match '/:controller/:action/:id' => '#index'
  match '/:controller/:action/:id.:format' => '#index'
end

app/controllers/task_imports_controller.rb
########################################################################
# File::    task_imports_controller.rb
# (C)::     Hipposoft 2008
#
# Purpose:: Import task definition data from external sources.
# ----------------------------------------------------------------------
#           30-Mar-2008 (ADH): Created.
########################################################################

class TaskImportsController < ApplicationController

  uses_prototype( :only => [ :create, :edit, :update ] )

  require 'zlib'
  require 'tempfile'
  require 'rexml/document'

  # Security.

  before_filter( :permitted? )

  # Take the file data from the 'new' view form and 'create' an "import
  # session"; that is, parse the file and generate an intermediate
  # representation of the tasks therein. Render an 'edit' view where the
  # user can 'edit' the "import session", by changing titles etc. of the
  # task list obtained from the file.
  #
  def create

    # Set up a new TaskImport session object and read the XML file details

    xmlfile = params[ :import ][ :xmlfile ] || ''
    @import = TaskImport.new
    @import.project_id = @current_user.control_panel.project_id

    if ( xmlfile == '' ) # Empty string = nothing chosen, else a file object

      flash[ :error ] = "Please choose a file before using the 'Analyse' button."

    else

      # The user selected a file to upload, so process it

      begin

        # We assume XML files always begin with "<" in the first byte and
        # if that's missing then it's GZip compressed. That's true in the
        # limited case of project files.

        xmlfile = xmlfile.tempfile
        byte = xmlfile.getc()
        xmlfile.rewind()

        xmlfile       = Zlib::GzipReader.new( xmlfile ) if ( byte != '<'[ 0 ] )
        xmldoc        = REXML::Document.new( xmlfile.read() )
        task_data     = TaskImport.get_tasks_from_xml( xmldoc )

        tasks         = task_data[ :tasks         ]
        parent_uids   = task_data[ :parent_uids   ]
        parent_titles = task_data[ :parent_titles ]

        if ( tasks.blank? )
          flash[ :error  ] = 'No usable tasks were found in that file'

        else
          @import.tasks         = tasks
          @import.parent_uids   = parent_uids
          @import.parent_titles = parent_titles
          @import.collapse      = @import.max_level

          @import.generate_filtered_task_list()

          flash[ :notice ] = 'Tasks read successfully. Please choose items to import.'
          render( { :action => :edit } )
          flash.delete( :notice ) and return # If not deleted, flash message persists for one fetch too many

        end

      rescue => error

        # REXML errors can be huge, including a full backtrace. It can cause
        # session cookie overflow and we don't want the user to see it. Cut
        # the message off at the first newline.

        lines = error.message.split("\n")
        flash[ :error ] = "Failed to read file: #{ lines[ 0 ] }"
        flash.delete( :notice ) # In case it got set above, but the render call then failed

      end
    end

    render( { :action => :new } )
    flash.delete( :error ) # If not deleted, flash message persists for one fetch too many
  end

  # Once the user has updated anything they need to update in the import
  # session 'edit'-like view (see also 'create' above), process the form
  # submission and import any real Tasks into the database if so requested
  # or re-process the input file if necessary.
  #
  def update

    @import = TaskImport.new( params[ :import ] )

    # Should this list now be collapsed, or should it be imported?

    unless ( params[ :do_collapse ].nil? )
      @import.generate_filtered_task_list()
      render( { :action => :edit } ) and return
    end

    # Import tasks from the filtered list submitted with the form, which holds
    # a combination of user-editable and hidden preset values.

    to_import = @import.filtered_tasks.reject { | task | task.import != '1' }

    if ( to_import.empty? )

      flash[ :error ] = 'No tasks were selected for import. Please select at least one task and try again.'

    else

      # Right, good to go! Do the import.

      begin
        Task.transaction do

          # Create a new project in passing?

          if params.has_key?( :do_import_new_task )
            project             = Project.new
            project.title       = @import.new_project_title
            project.customer_id = @import.new_project_customer_id
            project.description = "Created for XML bulk task import on #{ Time.now }"
            begin
              project.save!
            rescue => inner_error
              raise "Cannot create project: #{ inner_error }"
            end
          else
            project = Project.find( @import.project_id )
          end

          to_import.each do | source_task |
            Task.new do | destination_task |
              destination_task.title    = source_task.title
              destination_task.code     = source_task.code
              destination_task.duration = source_task.duration
              destination_task.billable = source_task.billable
              destination_task.project  = project
            end.save!
          end

          flash[ :notice ] = "#{ to_import.length } #{ to_import.length == 1 ? 'task' : 'tasks' } imported successfully."
          redirect_to( tasks_path() ) and return
        end

      rescue => error
        flash[ :error ] = "Unable to import tasks: #{ error }"

      end

    end

    render( { :action => :edit } )
    flash.delete( :error )
  end

private

  # Is the current action permitted?
  #
  def permitted?
    appctrl_not_permitted() if ( @current_user.restricted? )
  end
end

app/helpers/task_imports_helper.rb
########################################################################
# File::    task_imports_helper.rb
# (C)::     Hipposoft 2008
#
# Purpose:: Support functions for views related to Task Import objects.
#           See controllers/task_imports_controller.rb for more.
# ----------------------------------------------------------------------
#           04-Jan-2008 (ADH): Created.
########################################################################

module TaskImportsHelper

  # Generate a project selector for the project to which imported tasks will
  # be assigned. HTML is output which is suitable for inclusion in a table
  # cell or other similar container. Pass the form object being used for the
  # task import view and optional string to add as a prefix to each line of
  # output.
  #
  # At least one active project must exist when this method is called, else
  # the output string will be empty.
  #
  def timphelp_project_selector( form, line_prefix = '' )
    unless ( Project.active.count.zero? )
      output = apphelp_project_selector(
                 'import_project_id',
                 'import[project_id]',
                 @current_user.control_panel.project_id
               ).gsub( /^/, line_prefix )
    else
      output = ''
    end

    return output.html_safe()
  end

  # Generate a selector menu for collapsing a task tree to a given level. Pass
  # the containing form, the maximum integer level to show and an optional
  # string to add as a prefix to each line of output.
  #
  def timphelp_collapse_selector( form, max_level, line_prefix = '' )
    levels = []

    0.upto( max_level ) do | level |
      levels[ level ] = [ "Outline level #{ level }", level ]
    end

    return apphelp_select(
             form,
             :collapse,
             levels,
             false
           ).gsub( /^/, line_prefix ).html_safe()
  end
end

app/views/task_imports/edit.html.erb
      <h1><%= apphelp_heading() %></h1>

      <%=
          form_for(
            :import,
            {
              :url    => task_imports_path(),
              :html   => { :id     => 'import' },
              :method => :put
            }
          ) do | f |
      %>
        <p>
          The tasks found in the file are listed below. Only items with a ticked
          check box in the "Import?" column will be imported. The menu below the
          task list selects the project to which all tasks will be assigned. The
          default project is chosen in your
          <%= link_to( 'account settings', edit_user_path( @current_user ) ) %>.
        </p>

        <table class="bulk_task_import">

          <tr class="info">
            <th>&nbsp;Name</th>
            <th>Code</th>
            <th class="centred">Duration<br />(hours)</th>
            <th class="centred">
              Billable?<br />
              <script type="text/javascript">
                check_box_toggle_field( 'toggle_billable', 'billable' );
              </script>
            </th>
            <th class="centred">
              Import?<br />
              <script type="text/javascript">
                check_box_toggle_field( 'toggle_import', 'import' );
              </script>
            </th>
          </tr>

<%
   # Check for duplicated titles

   titles = {}
   dupes  = 0

   @import.filtered_tasks.each do | task |
     if ( titles[ task.title ] == true )
       dupes += 1
       titles[ task.title ] = dupes
     elsif ( titles[ task.title ].nil? )
       titles[ task.title ] = true
     end
   end

   billable_by_default = Task.new.billable
   breadcrumb          = nil
-%>
<%
   @import.filtered_tasks.each_index do | index |
     task = @import.filtered_tasks[ index ]
-%>
<%   
     current_breadcrumb = @import.filtered_parent_titles[ index ].join( ': ' )
     if ( breadcrumb != current_breadcrumb )
       breadcrumb = current_breadcrumb
-%>
          <tr class="breadcrumb">
            <td colspan="5">
              <strong>Outline level <%= task.level %></strong><% unless ( breadcrumb.empty? ) -%>&nbsp;&nbsp;<%= breadcrumb %><% end %>
            </td>
          </tr>

<%   end -%>
          <tr class="<%= cycle( 'even', 'odd' ) -%>">
            <td class="task_title">
              <%= titles[ task.title ] != true ? "<span class=\"dup\">#{ titles[ task.title] }:</span>" : '&nbsp;'.html_safe() %>
              <%= text_field_tag( "import[filtered_tasks][#{ index }][title]", task.title, { :size => 50, :class => 'task_title' } ) %>
              &nbsp;
            </td>
            <td>
              <%= text_field_tag( "import[filtered_tasks][#{ index }][code]", task.code, { :size => 16 } ) %>
            </td>
            <td class="centred">
              <%= text_field_tag( "import[filtered_tasks][#{ index }][duration]", task.duration, { :maxlength => 6, :size => 6, :class => 'centred' } ) %>
            </td>
            <td class="centred">
              <%= check_box_tag( "import[filtered_tasks][#{ index }][billable]", '1', billable_by_default, { :class => 'checkbox billable' } ) %>
            </td>
            <td class="centred">
              <%= check_box_tag( "import[filtered_tasks][#{ index }][import]", '1', true, { :class => 'checkbox import' } ) %>
            </td>
          </tr>

<% end -%>
        </table>
<% if ( dupes > 0 ) -%>

        <p class="centred">
          <strong>Warning!</strong>
          Some task titles are identical. Consider renaming them if importing.
        </p>
<% end -%>

        <!-- Remember any other information about tasks across form submissions -->

<%
   @import.filtered_tasks.each_index do | index |
     task = @import.filtered_tasks[ index ]
-%>
        <%= hidden_field_tag( "import[filtered_tasks][#{ index }][level]", task.level ) %>
        <%= hidden_field_tag( "import[filtered_tasks][#{ index }][tid]",   task.tid   ) %>
        <%= hidden_field_tag( "import[filtered_tasks][#{ index }][uid]",   task.uid   ) %>
<%   
     @import.filtered_parent_uids[ index ].each_index do | parent_index |
       uid   = @import.filtered_parent_uids[   index ][ parent_index ]
       title = @import.filtered_parent_titles[ index ][ parent_index ]
-%>
        <%= hidden_field_tag( "import[filtered_parent_uids][#{ index }][#{ parent_index }]", uid ) %>
        <%= hidden_field_tag( "import[filtered_parent_titles][#{ index }][#{ parent_index }]", title ) %>
<%   end -%>
<% end   -%>
<%
   @import.tasks.each_index do | index |
     task = @import.tasks[ index ]
-%>
        <%= hidden_field_tag( "import[tasks][#{ index }][level]",    task.level    ) %>
        <%= hidden_field_tag( "import[tasks][#{ index }][tid]",      task.tid      ) %>
        <%= hidden_field_tag( "import[tasks][#{ index }][uid]",      task.uid      ) %>
        <%= hidden_field_tag( "import[tasks][#{ index }][code]",     task.code     ) %>
        <%= hidden_field_tag( "import[tasks][#{ index }][title]",    task.title    ) %>
        <%= hidden_field_tag( "import[tasks][#{ index }][duration]", task.duration ) %>
<%
     @import.parent_uids[ index ].each_index do | parent_index |
       uid   = @import.parent_uids[   index ][ parent_index ]
       title = @import.parent_titles[ index ][ parent_index ]
-%>
        <%= hidden_field_tag( "import[parent_uids][#{   index }][#{ parent_index }]", uid   ) %>
        <%= hidden_field_tag( "import[parent_titles][#{ index }][#{ parent_index }]", title ) %>
<%   end -%>
<% end   -%>

        <!-- What next? -->

        <p></p>
        <table class="bulk_task_import">
          <tr>
            <th class="right">Now EITHER</th>
            <td>
              Assign all tasks to
<%= timphelp_project_selector( f, '          ' ) %>
              and
              <%= f.submit( 'import selected tasks', { :name => 'do_import', :disable_with => 'Importing...' } ) %>
            </td>
          </tr>
          <tr>
            <th class="right">OR</th>
            <td>
              <table class="bulk_task_import">
                <tr>
                  <td class="right">Create new project with title:&nbsp;</td>
                  <td>
                    <%= f.text_field( :new_project_title ) %>
                  </td>
                </tr>
<%          unless ( ( customers = Customer.active ).empty? ) -%>
                <tr>
                  <td class="right narrow">for customer:&nbsp;</td>
                  <td>
                    <%= f.collection_select(
                      :new_project_customer_id,
                      customers,
                      :id,
                      :title,
                      { :size => [ customers.size, 10 ].min, :include_blank => 'None' }
                    ) %>
                  </td>
                </tr>
<%          end -%>
                <tr>
                  <td class="right narrow">and:&nbsp;</td>
                  <td>
                    <%= f.submit( 'import into new project', { :name => 'do_import_new_task', :disable_with => 'Importing...' } ) %>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
<% unless ( @import.max_level.zero? ) -%>
          <tr>
            <th class="right narrow">OR</th>
            <td>
              Collapse tasks above
<%= timphelp_collapse_selector( f, @import.max_level, '          ' ) %>
              and
              <%= f.submit( 'generate new task list', { :name => 'do_collapse', :disable_with => 'Generating...' } ) %>
            </td>
          </tr>
<% end -%>
          <tr>
            <th class="right">OR</th>
            <td>
              <%= link_to( 'Cancel and choose another file', new_task_imports_path() ) %>   
            </td>
          </tr>
          <tr>
            <th class="right">OR</th>
            <td>
              <%= link_to( 'Cancel and return home', home_path() ) %>   
            </td>
          </tr>
        </table>

      <% end %>

app/views/task_imports/new.html.erb
      <h1><%= apphelp_heading() %></h1>

<% if ( Project.active.count.zero? ) -%>
      <p>
        There are no projects defined. You must
        <%= link_to( 'create at least one', new_project_path() ) %> before you
        can import any tasks.
      </p>
<% else -%>
      <%= form_for( :import, { :url => { :action => 'create' }, :html => { :id => 'import', :multipart => true } } ) do | f | %>

        <p>
          TrackRecord can import tasks <%= help_link( :xml_import ) %> from XML
          format files exported by planning applications such as
          <a href="http://sourceforge.net/projects/projectlibre/">ProjectLibre</a>,
          <a href="http://sourceforge.net/projects/openproj/">OpenProj</a>
          or <a href="http://office.microsoft.com/project/">Microsoft Project</a>.
        </p>

        <p>
          Choose an XML file stored locally on your computer using
          the button below, then use the "Analyse" button to continue. Please
          be patient. Large project files can take a while to upload and analyse.
          To reduce upload time, <a href="http://www.gzip.org/">GZip</a> the XML
          file first.
        </p>

        <%= f.file_field 'xmlfile' %>
        <%= f.submit( 'Analyse', { :name => 'import[analyse]', :disable_with => 'Analysing...' } ) %>

      <% end %>
<% end -%>
    
      <p>
        <%= link_to( 'Cancel and return home', home_path() ) %>
      </p>