config/routes.rb
Trackrecord::Application.routes.draw do

  # Map root to the User account home page. The "root" mapping is so that
  # "root_url" exists, since the open_id_authentication plugin requires it.

  match '/' => 'users#home'
  match '/' => 'users#home', :as => :home

  # Mapping for the OpenID login system. The signin and signout
  # entries are for more readable paths in views; they're just
  # aliases for 'new' and 'destroy' actions.

  get '/session' => 'sessions#create', :as  => :open_id_complete

  resource :session

  match '/signin'  => 'sessions#new',     :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout

  # Allow in-progress account signup to be cancelled

  match '/users/cancel/:id' => 'users#cancel', :as => :user_cancel

  # Get common named routes for our resources. Don't be confused by the rather
  # esoteric use of Ruby block syntax here - this is just defining some nested
  # routes; e.g. customers have many tasks, so tasks are defined as resources
  # within customers. The longhand equivalent would be:
  #
  #   resources :customers do
  #     resources :tasks
  #   end
  #
  # ...and the Rails 2 equivalent used to be:
  #
  #  map.resources :customers, :has_many => [ :tasks ]

  resources( :customers      ) { resources :tasks                            }
  resources( :projects       ) { resources :tasks                            }
  resources( :control_panels ) { resources :tasks                            }
  resources( :tasks          ) { resources :users; resources :timesheet_rows }
  resources( :timesheets     ) { resources :timesheet_rows                   }

  resources( :users ) do
    resources :tasks
    resources :timesheets

    resources :saved_reports do
      get 'delete', :on => :member

      # This route is rather confusing and was determined by trial and error.
      # The intention is to get a variant of "new" which takes an ID, for the
      # "copy a report" case. The below achieves it (see "rake routes" and
      # look for "saved_reports#new" - it appears twice in different forms).
      # It also creates "user_saved_report_copy_<foo>()" methods.

      get 'new', :to => 'saved_reports#new', :as => 'copy'
    end

    resource :saved_reports_by_task,     :controller => :saved_reports_by_task,     :only => :create
    resource :saved_reports_by_project,  :controller => :saved_reports_by_project,  :only => :create
    resource :saved_reports_by_customer, :controller => :saved_reports_by_customer, :only => :create
    resource :saved_reports_by_user,     :controller => :saved_reports_by_user,     :only => :create
  end

  resources :audits
  resources :reports
  resources :charts
  resource  :task_imports
  resources :trees

  resources :help

  resource  :saved_report_auto_title, :only => :show
  resource  :timesheet_force_commit,  :only => [ :new, :create ]

  # Finally, the normal default rules at lowest priority

  match '/:controller/:action/:id' => '#index'
  match '/:controller/:action/:id.:format' => '#index'
end

app/helpers/tasks_helper.rb
########################################################################
# File::    tasks_helper.rb
# (C)::     Hipposoft 2008
#
# Purpose:: Support functions for views related to Task objects. See
#           controllers/tasks_controller.rb for more.
# ----------------------------------------------------------------------
#           04-Jan-2008 (ADH): Created.
########################################################################

module TasksHelper

  # Return HTML suitable for an edit form, providing a grouped list of
  # projects that can be assigned to the task. The list is grouped by
  # customer in default customer sort order, along with a 'None' entry
  # for unassigned projects. Pass the task object being edited.

  def taskhelp_project_selector( task )
    return apphelp_project_selector(
      'task_project_id',
      'task[project_id]',
      task.project_id,
      true
    )
  end

  # Return HTML showing the remaining hours on a task, or a label
  # indicating overrun. Pass the number of hours and the expected
  # task duration.

  def taskhelp_remaining( hours, duration )
    if ( hours > duration and duration != 0 )
      return '<span class="overrun">Overrunning</span>'.html_safe()
    else
      return apphelp_hours( 0 ) if ( duration == 0 )
      return apphelp_hours( duration - hours )
    end
  end

  # Return HTML showing the number of hours overrun on a task, or
  # a label indicating no overrun. Pass the number of hours and the
  # expected task duration.

  def taskhelp_overrun( hours, duration )
    if ( hours > duration and duration != 0 )
      return apphelp_hours( hours - duration )
    else
      return '<span class="no_overrun">None</span>'.html_safe()
    end
  end

  # Return a name of a given task's associated project, for use in list views.

  def taskhelp_project( task )
    return '-'.html_safe() if ( task.project.nil? )
    return apphelp_augmented_link( task.project )
  end

  # Return a name of a given task's associated customer, for use in list views.

  def taskhelp_customer( task )
    return '-'.html_safe() if ( task.project.nil? or task.project.customer.nil? )
    return apphelp_augmented_link( task.project.customer )
  end

  # Return a formatted duration for the given task, for use in list views.

  def taskhelp_duration( task )
    return apphelp_string_hours( task.duration.to_s, '0', '?' )
  end

  # Return list actions appropriate for the given task.

  def taskhelp_actions( task )
    if ( @current_user.admin? or ( task.active and @current_user.manager? ) )
      actions = [ 'edit' ]
      actions.push( 'delete' ) if ( @current_user.admin? )
    else
      actions = []
    end

    actions.push( 'show' )
    return actions
  end

  # Return an HTML class name appropriate for a billable or not billable task
  # according to the given task or, if given a boolean, the value of that
  # boolean where 'true' means 'billable'
  #
  # Note that an additional class name may be included for active/inactive
  # tasks (but not when a boolean is given, obviously!).
  #
  def taskhelp_billable_class( task_or_boolean )
    task_or_boolean = task_or_boolean.billable if ( task_or_boolean.is_a?( Task ) )
    return ( task_or_boolean ? "task_billable" : "task_not_billable" )
  end

  # Return an HTML fragment giving help on billable versus non-billable tasks.
  #
  def taskhelp_billable_help
    return (
      "Names of billable or non-billable tasks are shown as follows: " <<
      "'<span class=\"#{ taskhelp_billable_class( true  ) }\">billable</span>', " <<
      "'<span class=\"#{ taskhelp_billable_class( false ) }\">not billable</span>'."
    ).html_safe()
  end

  # As taskhelp_billable_class, but for active/inactive tasks.
  #
  def taskhelp_active_class( task_or_boolean )
    task_or_boolean = task_or_boolean.active if ( task_or_boolean.is_a?( Task ) )
    return ( task_or_boolean ? "task_active" : "task_inactive" )
  end

  # As taskhelp_billable_help, but for active/inactive tasks.
  #
  def taskhelp_active_help
    return (
      "Names of active or inactive tasks are shown as follows: " <<
      "'<span class=\"#{ taskhelp_active_class( true  ) }\">active</span>', " <<
      "'<span class=\"#{ taskhelp_active_class( false ) }\">inactive</span>'."
    ).html_safe()
  end

  # Generate a YUI tree task selector. Pass a form builder object in the first
  # parameter (e.g. "bar" in "form_for @foo do | bar |"). The "object_name"
  # field is used to generate a unique ID and name for a hidden element which
  # carries IDs of selected YUI tree nodes, in the form "name[task_ids][]" - as
  # used by non-JS SELECT lists elsewhere. In the form submission processing
  # code, you must handle the use of special IDs in the YUI tree ("P" prefix
  # for Projects, "C" prefix for Customers, no prefix for tasks).
  #
  # In the next parameter optionally pass an options hash with keys and values
  # as shown below; any omitted key/value pair results in the described default
  # value being used instead.
  #
  #   Key              Meaning
  #   =========================================================================
  #   :inactive        If 'true', only inactive tasks, customers and projects
  #                    are shown in the selector. By default, only active items
  #                    will be shown.
  #
  #   :restricted_by   The task/project/customer list for currently logged in
  #                    users who are restricted is always restricted by that
  #                    user's permitted task list no matter what you set here.
  #                    If the current user is privileged, though, then passing
  #                    in a User object results in restriction by that user's
  #                    permitted task list. By default there is no restriction
  #                    so for privileged currently logged in users, all tasks
  #                    would be shown.
  #
  #   :included_tasks  If you know up-front a full list of tasks to show, then
  #                    pass them in here. Only items in the included list will
  #                    be shown. IDs get passed to the XHR handler, among other
  #                    things. This is NOT a security feature - see
  #                    ":restricted_by" for that.
  #
  #   :selected_tasks  An array of tasks to be initially selected in the tree.
  #                    May be empty. By default no tasks are selected. Ideally
  #                    the list should include no tasks that the current user
  #                    or 'restricted_by' key would hide, but if it does, they
  #                    simply won't be shown or selected and only the task IDs
  #                    will appear in HTML output.
  #
  #   :suffix_html     Beneath the text area gadget listing selected tasks is
  #                    a "Change..." link which pops up the Leightbox overlay
  #                    containing the YUI tree. If you want any extra HTML
  #                    inserted directly after the "</a>" of this link but
  #                    before the (hidden) DIV enclosing the tree, use this
  #                    option to include it. To keep things tidy, ensure that
  #                    the string is terminated by a newline ("\n") character.
  #
  #   :change_text     Speaking of the "Change..." link - alter its text with
  #                    this option, or omit for the default "Change..." string.
  #
  #   :params_name     Name to use in params instead of "task_ids", so that
  #                    instead of reading "params[form.object_name][:task_ids]"
  #                    in the controller handling the form submission, you read
  #                    the params entry corresponding to the given name.
  #
  # See also "taskhelp_degrading_selector" for JS/non-JS degrading code.
  #
  # Note that projects with no customer, or tasks with no project will not be
  # shown in the tree; "unassigned" projects and customers are really just an
  # administrative convenience during times when things might be in the
  # process of being reassigned, or right at the start when someone is setting
  # up new tasks, projects and customers, not necessarily starting with the
  # customer definition first.
  #
  def taskhelp_tree_selector( form, options = {} )

    inactive       = options.delete( :inactive       )
    restricted_by  = options.delete( :restricted_by  )
    included_tasks = options.delete( :included_tasks )
    selected_tasks = options.delete( :selected_tasks ) || []
    suffix_html    = options.delete( :suffix_html    ) || ''
    change_text    = options.delete( :change_text    ) || 'Change...'
    params_name    = options.delete( :params_name    ) || :task_ids

    # Callers may generate trees restricted by the current user, but if that
    # user is themselves privileged their restricted task list will be empty
    # (because they can see anything). The simplest way to deal with this is
    # to clear the restricted user field in such cases.

    restricted_by = nil unless ( restricted_by.nil? || restricted_by.restricted? )

    # Based on the restricted task list - or otherwise - try to get at the root
    # customer array as easily as possible, trying to avoid pulling all tasks
    # out of the database. This is a bit painful either way, but usually a
    # restricted user will have a relatively small set of tasks assigned to
    # them so doing the array processing in Ruby isn't too big a deal.

    if ( @current_user.restricted? )
      permitted_tasks = @current_user.active_permitted_tasks()
    else
      permitted_tasks = restricted_by.active_permitted_tasks() unless ( restricted_by.nil? )
    end

    unless ( included_tasks.nil? )
      if ( permitted_tasks.nil? )
        permitted_tasks  = included_tasks
      else
        permitted_tasks &= included_tasks
      end
    end

    if ( permitted_tasks.nil? )
      root_customers = Customer.all
    else

app/views/tasks/_edit.html.erb
<%= error_messages_for :record %>
<%= form_for( @record ) do | f | %>
  <%= f.hidden_field( :lock_version ) %>
  <table class="editing_table">
    <tr class="editing_row">
      <th>Task title (required)</th>
      <td><%= f.text_field( :title ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Task code</th>
      <td><%= f.text_field( :code ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Expected duration (in hours, required)</th>
      <td><%= f.text_field( :duration, { :maxlength => 6 } ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Description</th>
      <td><%= f.text_area( :description, { :cols => 40, :rows => 4 } ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Tick if billable:</th>
      <td><%= f.check_box( :billable ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Assigned to project?</th>
      <td>
<% if ( ( projects = Project.active ).empty? ) -%>
        There are no active projects.
<% else -%>
<%= taskhelp_project_selector( @record ) %>
<% end -%>
        <p>
          Users cannot add a task to timesheets unless the task is assigned
          to a project and the project is assigned to a customer.
          <% if ( action_name == 'edit' || action_name == 'update' ) -%>
          Any timesheets already including the task will be unaffected.
          <% end -%>
        </p>
      </td>
    </tr>

<% if ( action_name == 'edit' or action_name == 'update' ) -%>
    <tr class="editing_row">
      <th>Active?</th>
      <td>
<%= f.select( :active, [ [ 'Active', true ], [ 'Inactive', false ] ] ) %>
      <b><i>Warning</i></b> &ndash; once made inactive, a task cannot be edited again.
      </td>
    </tr>
<% end -%>
  </table>

  <p>
<% if ( action_name == 'new' or action_name == 'create' ) -%>
    <%= f.submit( 'Create', { :disable_with => 'Creating...' } ) %>
<% else -%>
    <%= f.submit( 'Update', { :disable_with => 'Updating...' } ) %>
    else <%= link_to( 'cancel and show details', @record ) %>
<% end -%>
    or <%= link_to( 'cancel and list tasks', tasks_path() ) %>
    or <%= link_to( 'cancel and add a new project', new_project_path() ) %>.
  </p>
<% end %>

app/views/tasks/delete.html.erb
<div class="icon_page warning">

  <h1>Delete task<%= @record.title.blank? ? '' : " '#{ @record.title }'" %>?</h1>
  <h2>Warning!</h2>

  <p>
    Only use the 'delete' button if you are <strong>absolutely sure</strong>
    that you wish to delete this task. Any timesheets with rows referring to
    the task will have those rows automatically deleted. Work packets booked
    for those rows will be deleted in passing; there will be no record
    remaining of any time booked to the task. <strong>The action cannot be
    undone.</strong>
  </p>

  <div class="centred">
    <%= form_for( :task, :url => { :action => 'destroy', :id => @record.id }, :html => { :method => 'delete' } ) do | f | %>
      <%= f.submit( 'Delete task', { :disable_with => 'Deleting...' } ) %>
    <% end %>
  </div>

  <p>
    <%= link_to( 'Cancel and show details', @record      ) %> |
    <%= link_to( 'Cancel and list tasks',   tasks_path() ) %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1><%= apphelp_heading() %></h1>
<%= render :partial => 'edit' %>

app/views/tasks/index.html.erb
<%= render(
      {
        :partial => 'shared/active_inactive_list',
        :locals  =>
        {
          :model          => 'task',
          :active         => @active_tasks,
          :inactive       => @inactive_tasks,
          :columns        => @columns,
          :actions_method => 'taskhelp_actions'
        }
      }
    )
%>
      <h2>Find tasks</h2>

<%=
    render(
      :partial => 'shared/search',
      :locals  => {
        :path    => tasks_path(),
        :prompt  => 'Search task, project and customer titles and task codes',
        :dprompt => 'between task addition date',
        :years   => Task.used_range()
      }
    )
%>

app/views/tasks/new.html.erb
<h1><%= apphelp_heading() %></h1>
<%= render :partial => 'edit' %>

app/views/tasks/show.html.erb
    <h1><%= apphelp_heading() %></h1>
    
    <h2><%= h( @record.title ) %> (<%= apphelp_commit_label( @record ) %>)</h2>

<%= render( :partial => 'shared/task_info', :locals => { :task => @record } ) %>

<% if ( @current_user.privileged? ) -%>
    <p>
      Note that managers and administrators may commit hours against
      tasks even if not associated with them. All commits are recorded
      in the <%= link_to( 'audit trail', audits_path() ) %>.
    </p>

    <div class="display_actions">
      <%=
          render(
            :partial => 'shared/report_button',
            :locals  => {
              :user => @current_user,
              :item => @record
            }
          )
      %>,
<%   if ( @current_user.admin? or ( @current_user.manager? and @record.active ) ) %>
      <%= link_to( 'edit this task', edit_task_path( @record ) ) %>,
<%   end -%>
      <%= link_to( 'list tasks', tasks_path() ) %>
      or <%= link_to( 'return home', home_path() ) %>
    </div>
<% end -%>