config/routes.rb
Trackrecord::Application.routes.draw do

  # Map root to the User account home page. The "root" mapping is so that
  # "root_url" exists, since the open_id_authentication plugin requires it.

  match '/' => 'users#home'
  match '/' => 'users#home', :as => :home

  # Mapping for the OpenID login system. The signin and signout
  # entries are for more readable paths in views; they're just
  # aliases for 'new' and 'destroy' actions.

  get '/session' => 'sessions#create', :as  => :open_id_complete

  resource :session

  match '/signin'  => 'sessions#new',     :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout

  # Allow in-progress account signup to be cancelled

  match '/users/cancel/:id' => 'users#cancel', :as => :user_cancel

  # Get common named routes for our resources. Don't be confused by the rather
  # esoteric use of Ruby block syntax here - this is just defining some nested
  # routes; e.g. customers have many tasks, so tasks are defined as resources
  # within customers. The longhand equivalent would be:
  #
  #   resources :customers do
  #     resources :tasks
  #   end
  #
  # ...and the Rails 2 equivalent used to be:
  #
  #  map.resources :customers, :has_many => [ :tasks ]

  resources( :customers      ) { resources :tasks                            }
  resources( :projects       ) { resources :tasks                            }
  resources( :control_panels ) { resources :tasks                            }
  resources( :tasks          ) { resources :users; resources :timesheet_rows }
  resources( :timesheets     ) { resources :timesheet_rows                   }

  resources( :users ) do
    resources :tasks
    resources :timesheets

    resources :saved_reports do
      get 'delete', :on => :member

      # This route is rather confusing and was determined by trial and error.
      # The intention is to get a variant of "new" which takes an ID, for the
      # "copy a report" case. The below achieves it (see "rake routes" and
      # look for "saved_reports#new" - it appears twice in different forms).
      # It also creates "user_saved_report_copy_<foo>()" methods.

      get 'new', :to => 'saved_reports#new', :as => 'copy'
    end

    resource :saved_reports_by_task,     :controller => :saved_reports_by_task,     :only => :create
    resource :saved_reports_by_project,  :controller => :saved_reports_by_project,  :only => :create
    resource :saved_reports_by_customer, :controller => :saved_reports_by_customer, :only => :create
    resource :saved_reports_by_user,     :controller => :saved_reports_by_user,     :only => :create
  end

  resources :audits
  resources :reports
  resources :charts
  resource  :task_imports
  resources :trees

  resources :help

  resource  :saved_report_auto_title, :only => :show
  resource  :timesheet_force_commit,  :only => [ :new, :create ]

  # Finally, the normal default rules at lowest priority

  match '/:controller/:action/:id' => '#index'
  match '/:controller/:action/:id.:format' => '#index'
end

app/models/project.rb
########################################################################
# File::    project.rb
# (C)::     Hipposoft 2007
#
# Purpose:: Describe the behaviour of Project objects. See below for
#           more details.
# ----------------------------------------------------------------------
#           24-Dec-2007 (ADH): Created.
########################################################################

class Project < TaskGroup

  audited( :except => [
    :lock_version,
    :updated_at,
    :created_at,
    :id
  ] )

  # A Project is an organisational unit for the benefit of the
  # timesheet system operator. Projects consist of a series of
  # tasks. The project's expected duration is the sum of the
  # expected durations of its tasks. ControlPanel objects refer
  # to Projects as the default project used in task creation.
  # Each project belongs to a single Customer.

  belongs_to( :customer )

  has_many( :control_panels )
  has_many( :tasks )

  accepts_nested_attributes_for( :tasks, reject_if: proc() { | attrs | attrs[ 'title' ] .blank? } )

  scope :unassigned, -> { where( :customer_id => nil ) }

  attr_protected() # Necessary for unknown reasons, Rails issues?

  USED_RANGE_COLUMN = 'created_at' # For the Rangeable base class of TaskGroup

  validate( :customer_is_active )

  # Some default properties are dynamic, so assign these here rather than
  # as defaults in a migration.
  #
  # Parameters:
  #
  #   Optional hash used for instance initialisation in the traditional way
  #   for an ActiveRecord subclass.
  #
  #   Optional User object. A default customer is taken from that user's
  #   control panel data, if available.
  #
  def initialize( params = nil, user = nil )
    super( params )

    if ( params.nil? )
      self.active = true
      self.code   = "PID%04d" % Project.count

      if ( user and user.control_panel )
        cp = user.control_panel
        self.customer = cp.customer if ( cp.customer and cp.customer.active )
      end
    end
  end

  # Update an object with the given attributes. This is done by a
  # special model method because changes of the 'active' flag have
  # side effects for other associated objects. THE CALLER **MUST**
  # USE A TRANSACTION around a call to this method. There is no
  # need to call here unless the 'active' flag state is changing.
  # Pass in 'true' to update associated tasks, else 'false'. If
  # omitted, defaults to 'true'.
  #
  def update_with_side_effects!( attrs, update_tasks = true )
    active = self.active
    self.update_attributes!( attrs )

    # If the active flag has changed, deal with repercussions.

    if ( update_tasks and attrs[ :active ] != active )
      self.tasks.all.each do | task |
        task.update_with_side_effects!( { :active => attrs[ :active ] } )
      end
    end
  end

  # As update_with_side_effects!, but destroys things rather than
  # updating them. Pass 'true' to destroy associated tasks, else
  # 'false'. If omitted, defaults to 'true'.
  #
  def destroy_with_side_effects( destroy_tasks = true )
    if ( destroy_tasks )
      self.tasks.all.each do | task |
        task.destroy()
      end
    else
      Task.where( :project_id => self.id ).update_all( :project_id => nil )
    end

    self.destroy()
  end

private

  # Run via "validate".
  #
  def customer_is_active()
    unless ( ( not self.active ) or self.customer.nil? or self.customer.active )
      errors.add( :base, 'Active projects can only be associated with active customers' )
    end
  end
end

app/controllers/projects_controller.rb
########################################################################
# File::    projects_controller.rb
# (C)::     Hipposoft 2008
#
# Purpose:: Manage Project objects. See models/project.rb for more.
# ----------------------------------------------------------------------
#           04-Jan-2008 (ADH): Created.
########################################################################

class ProjectsController < ApplicationController

  # In place editing and security

  safe_in_place_edit_for( :project, :title )
  safe_in_place_edit_for( :project, :code  )

  before_filter( :can_be_modified?, :only => [ :edit, :update, :set_project_title, :set_project_code ] )

  uses_prototype( :only => :index )

  # List projects.
  #
  def index

    # Set up the column data; see the index helper functions in
    # application_helper.rb for details.

    @columns = [
      { :header_text  => 'Customer',      :sort_by      => 'customers.title', :value_helper   => :projecthelp_customer },
      { :header_text  => 'Project title', :value_method => :title,            :value_in_place => true                  },
      { :header_text  => 'Project code',  :value_method => :code,             :value_in_place => true                  },
      { :header_text  => 'Created at',    :value_method => :created_at,       :value_helper   => :apphelp_created_at   },
    ]

    # Get the basic options hash from ApplicationController, then work out
    # the conditions on objects being fetched, including handling the search
    # form data.

    options        = appctrl_index_assist( Project )
    active_vars    = { :active => true  }
    inactive_vars  = { :active => false }
    conditions_sql = "WHERE ( projects.active = :active )\n"

    # The user may only be able to see projects associated with tasks matching
    # a specific list of IDs.

    restrictions_sql = ''

    if ( @current_user.restricted? )
      restrictions_sql = 'INNER JOIN tasks ON ( '
      if ( @current_user.task_ids.empty? )
        restrictions_sql << 'tasks.id = -1' # Never matches - forces no results
      else
        restrictions_sql << "tasks.project_id = projects.id AND tasks.id IN (#{ @current_user.task_ids.join( ',' ) } )"
      end
      restrictions_sql << " )\n"
    end

    # If asked to search for something, build extra conditions to do so.

    range_sql, range_start, range_end = appctrl_search_range_sql( Project )
    
    unless ( range_sql.nil? )
      search = "%#{ params[ :search ] }%" # SQL wildcards either side of the search string
      conditions_sql << "AND #{ range_sql } ( projects.title ILIKE :search OR projects.code ILIKE :search OR customers.title ILIKE :search )\n"

      vars = { :search => search, :range_start => range_start, :range_end => range_end }
      active_vars.merge!( vars )
      inactive_vars.merge!( vars )
    end

    # Sort order is already partially compiled in 'options' from the earlier
    # call to 'ApplicationController.appctrl_index_assist'.

    order_sql = "ORDER BY #{ options[ :order ] }, title ASC, code ASC"
    options.delete( :order )

    # Compile the main SQL statement. Select all columns of the project, fetching
    # customers where the project's customer ID matches those customer IDs, with
    # only projects containing tasks in the user's permitted task list (if any)
    # are included, returned in the required order.
    #
    # Due to restrictions in the way that DISTINCT works, I just cannot figure out
    # ANY way in SQL to only return unique projects while still matching the task
    # permitted ID requirement for restricted users. So, fetch duplicates, then
    # strip them out in Ruby afterwards (ouch).

    finder_sql  = "SELECT projects.* FROM projects\n" <<
                  "LEFT OUTER JOIN customers ON ( projects.customer_id = customers.id )\n" <<
                  "#{ restrictions_sql }\n" <<
                  "#{ conditions_sql   }\n" <<
                  "#{ order_sql        }"

    # Now paginate using this SQL. The only difference between the active and
    # inactive cases is the value of the variables passed to Active Record for
    # substitution into the final SQL query going to the database.

    @active_projects   = Project.paginate_by_sql( [ finder_sql, active_vars   ], options )
    @inactive_projects = Project.paginate_by_sql( [ finder_sql, inactive_vars ], options )

    # Now patch up the deficiencies of the SQL query (see comments above).

    if ( @current_user.restricted? )
      @active_projects.uniq!
      @inactive_projects.uniq!
    end
  end

  # The Application Controller provides generic implementations and
  # security sufficient for the other actions in this model. See its
  # comments for details.

  # Show the Project (via ApplicationController.appctrl_show).
  #
  def show
    appctrl_show( 'Project' )
  end

  # Show a 'Create Project' view (via ApplicationController.appctrl_new).
  #
  def new
    appctrl_new( 'Project' )
  end

  # Create a Project (via ApplicationController.appctrl_create).
  #
  def create
    appctrl_create( 'Project' )
  end

  # Update the project details. We may need to update associated tasks
  # too, so the update is wrapped in a transaction to allow the database
  # to roll back if anything goes wrong.
  #
  # @record is set by the "can_be_modified?" before_filter method.
  #
  def update
    begin
      Project.transaction do
        update_tasks = ! params[ :update_tasks ].nil?

        @record.update_with_side_effects!(
          params[ :project ],
          update_tasks
        )

        flash[ :notice ] = 'Project details updated'
        redirect_to( projects_path() )
      end

    rescue ActiveRecord::StaleObjectError
      flash[ :error ] = 'The project details were modified by someone else while you were making changes. Please examine the updated information before editing again.'
      redirect_to( project_path( @record ) )

    rescue => error
      flash[ :error ] = "Could not update project details: #{ error }"
      render( :action => 'edit' )

    end
  end

  # Projects should not normally be destroyed. Only administrators
  # can do this. Works via ApplicationController.appctrl_delete.
  #
  def delete
    appctrl_delete( 'Project' )
  end

  # Show an 'Are you sure?' prompt.
  #
  def delete_confirm
    return appctrl_not_permitted() unless ( @current_user.admin? )

    begin
      Customer.transaction do
        destroy_tasks = ! params[ :destroy_tasks ].nil?

        record = Project.find_by_id( params[ :id ] )
        record.destroy_with_side_effects( destroy_tasks )

        if ( destroy_tasks )
          message = 'Project and its tasks deleted'
        else
          message = 'Project deleted; its tasks were left alone'
        end

        flash[ :notice ] = message
        redirect_to( projects_path() )
      end

    rescue => error
      flash[ :error ] = "Could not destroy project: #{ error }"
      redirect_to( home_path() )

    end
  end

private

  # before_filter action - can the item in the params hash be modified by
  # the current user?
  #
  def can_be_modified?
    @record = Project.find_by_id( params[ :id ] )
    return appctrl_not_permitted() unless @record.can_be_modified_by?( @current_user )
  end
end

app/helpers/projects_helper.rb
########################################################################
# File::    projects_helper.rb
# (C)::     Hipposoft 2008
#
# Purpose:: Support functions for views related to Project objects. See
#           controllers/projects_controller.rb for more.
# ----------------------------------------------------------------------
#           04-Jan-2008 (ADH): Created.
########################################################################

module ProjectsHelper

  # Return a name of a given project's associated customer, for use
  # in list views.

  def projecthelp_customer( project )
    return '-'.html_safe() if ( project.customer.nil? )
    return apphelp_augmented_link( project.customer )
  end

  # Return list actions appropriate for the given project

  def projecthelp_actions( project )
    if ( @current_user.admin? or ( project.active and @current_user.manager? ) )
      actions = [ 'edit' ]
      actions << 'delete' if ( @current_user.admin? )
    else
      actions = []
    end

    actions.push( 'show' )
    return actions
  end

end

app/views/projects/_edit.html.erb
<h1><%= apphelp_heading() %></h1>

<%= error_messages_for :record %>
<%= form_for( @record ) do | f | %>
  <%= f.hidden_field( :lock_version ) %>
  <table class="editing_table">
    <tr class="editing_row">
      <th>Project title</th>
      <td><%= f.text_field( :title ) %> (required; must be unique)</td>
    </tr>

    <tr class="editing_row">
      <th>Project code</th>
      <td><%= f.text_field( :code ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Description</th>
      <td><%= f.text_area( :description, { :cols => 40, :rows => 4 } ) %></td>
    </tr>

    <tr class="editing_row">
      <th>Assigned to customer?</th>
      <td>
<% if ( ( customers = Customer.active ).empty? ) -%>
        There are no active customers.
<% else -%>
<%= f.collection_select(
  :customer_id,
  customers,
  :id,
  :title,
  { :size => [ customers.size, 10 ].min, :include_blank => 'None' }
) %>
<% end -%>
        <p>
          Users cannot add a project's tasks to timesheets unless the project
          is assigned to a customer.
          <% if ( action_name == 'edit' || action_name == 'update' ) -%>
          Any timesheets already including tasks from the project will be
          unaffected.
          <% end -%>
        </p>
      </td>
    </tr>

    <tr class="editing_row">
<% if ( action_name == 'edit' or action_name == 'update' ) -%>
      <th>Active?</th>
      <td>
<%=  f.select( :active, [ [ 'Active', true ], [ 'Inactive', false ] ] ) %>

<%   if ( @current_user.admin? ) -%>
        <p>
          If changing the 'active' state:
        </p>

        <p>
          <%= check_box_tag( 'update_tasks', '1', true ) %>
          Change associated tasks too
        </p>
<%   else -%>
        <p>
          If changing to inactive:
        </p>

        <p>
          <%= check_box_tag( 'update_tasks', '1', true ) %>
          Make associated tasks inactive too
        </p>
<%   end -%>

        <p>
          When a project is made inactive, all of its tasks may be made inactive
          too. Hours cannot be booked to inactive tasks. Once something is made
          inactive, it cannot be edited again. Only an administrator can make
          something active again.
        </p>
      </td>
<% 
   else # action is "new"/"create" rather than "edit"/"update"
-%>
      <th>Auto-create first task?</th>
      <td>
<%      if @record.tasks.empty?

          # Where here and not in the controller? It keeps this code, the
          # associated form hidden fields and the text explaining the nature
          # of the new task all within one place, easing maintenance.

          task          = Task.new
          task.billable = false
          task.duration = 0
          @record.tasks << task
        end -%>
<%=     f.fields_for( :tasks ) do | task_fields | -%>
        <%= task_fields.text_field( :title ) %>
        <%= task_fields.hidden_field( :code ) %>
        <%= task_fields.hidden_field( :billable ) %>
        <%= task_fields.hidden_field( :duration ) %>
<%      end -%>
        <p>
          If you provide a name above, a simple initial task will be created alongside
          the project.<br />
          It will have undefined (zero) expected duration and be marked as not billable.
        </p>
      </td>
<%
   end # Different output for "new"/"create" vs "edit"/"update"
-%>
    </tr>
  </table>

  <p>
<% if ( action_name == 'new' or action_name == 'create' ) -%>
    <%= f.submit( 'Create', { :disable_with => 'Creating...' } ) %>
<% else -%>
    <%= f.submit( 'Update', { :disable_with => 'Updating...' } ) %>
    else <%= link_to( 'cancel and show details', @record ) %>
<% end -%>
    or <%= link_to( 'cancel and list projects', projects_path() ) %>
    or <%= link_to( 'cancel and add a new customer', new_customer_path() ) %>.
  </p>
<% end %>

app/views/projects/delete.html.erb
<div class="icon_page warning">

  <h1>Delete project<%= @record.title.blank? ? '' : " '#{ @record.title }'" %>?</h1>
  <h2>Warning!</h2>

  <p>
    Only use the 'delete' button if you are <strong>absolutely sure</strong>
    that you wish to delete the project and, if the box next to the button is
    ticked, <em>all</em> of its associated tasks. <strong>The action cannot be
    undone.</strong>
  </p>

  <%= form_for( :project, :url => { :action => 'delete_confirm', :id => @record.id } ) do | f | %>
    <%= f.submit( 'Delete project', { :disable_with => 'Deleting...' } ) %>
    <%= label_tag :destroy_tasks do %>
      <%= check_box_tag( 'destroy_tasks' ) %>
      Delete associated tasks too?
    <% end %>
  <% end %>

  <p>
    <%= link_to( 'Cancel and show details',  @record         ) %> |
    <%= link_to( 'Cancel and list projects', projects_path() ) %>
  </p>

</div>

app/views/projects/edit.html.erb
<%= render :partial => 'edit' %>

app/views/projects/index.html.erb
<%= render(
      {
        :partial => 'shared/active_inactive_list',
        :locals  =>
        {
          :model          => 'project',
          :active         => @active_projects,
          :inactive       => @inactive_projects,
          :columns        => @columns,
          :actions_method => 'projecthelp_actions'
        }
      }
    )
%>
      <h2>Find projects</h2>

<%=
    render(
      :partial => 'shared/search',
      :locals  => {
        :path    => projects_path(),
        :prompt  => 'Search project and customer titles and project codes',
        :dprompt => 'between project addition date',
        :years   => Project.used_range()
      }
    )
%>

app/views/projects/new.html.erb
<%= render :partial => 'edit' %>

app/views/projects/show.html.erb
    <h1>Project details</h1>
    
    <h2><%= h( @record.title ) %> (<%= apphelp_commit_label( @record ) %>)</h2>

    <table class="display_table indented">
      <tr class="display_row">
        <th>Created at</th>
        <td><%= @record.created_at %></td>
      </tr>
      <tr class="display_row">
        <th>Code</th>
        <td><%= apphelp_h( @record.code ) %></td>
      </tr>
      <tr class="display_row">
        <th>Description</th>
        <td><%= apphelp_h( @record.description ) %></td>
      </tr>
      <tr class="display_row">
        <th>Associated customer</th>
        <td><%= @record.customer ? link_to( h( @record.customer.title ), @record.customer ) : 'None' %></td>
      </tr>
    </table>

<% if ( @current_user.privileged? ) -%>
    <p>
      The project has <%= pluralize( @record.tasks.size, 'associated task' ) %>.
<%   unless ( @record.tasks.empty? ) -%>
      A summary is given below. For full details, see the
      <%= link_to( 'report generator', new_user_saved_report_path( @current_user ) ) %>.
<%   end -%>
    </p>

<%   unless ( @record.tasks.empty? ) -%>
    <h2 id="item_breakdown_heading">Task breakdown</h2>
    <div id="item_breakdown_contents">

<%     @record.tasks.all.each do | task | -%>
      <h3>Task: <%= link_to( h( task.title ), task ) %></h3>

<%= render( :partial => 'shared/task_info', :locals => { :task => task } ) %>
<%     end -%>
<%   end -%>
    </div>

    <div class="display_actions">
      <%=
          render(
            :partial => 'shared/report_button',
            :locals  => {
              :user => @current_user,
              :item => @record
            }
          )
      %>,
<%     if ( @current_user.admin? or ( @current_user.manager? and @record.active ) ) %>
      <%= link_to( 'edit this project', edit_project_path( @record ) ) %>,
<%     end -%>
      <%= link_to( 'List projects', projects_path() ) %>
      or <%= link_to( 'return home', home_path() ) %>
    </div>
<% end -%>