config/routes.rb
Trackrecord::Application.routes.draw do

  # Map root to the User account home page. The "root" mapping is so that
  # "root_url" exists, since the open_id_authentication plugin requires it.

  match '/' => 'users#home'
  match '/' => 'users#home', :as => :home

  # Mapping for the OpenID login system. The signin and signout
  # entries are for more readable paths in views; they're just
  # aliases for 'new' and 'destroy' actions.

  get '/session' => 'sessions#create', :as  => :open_id_complete

  resource :session

  match '/signin'  => 'sessions#new',     :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout

  # Allow in-progress account signup to be cancelled

  match '/users/cancel/:id' => 'users#cancel', :as => :user_cancel

  # Get common named routes for our resources. Don't be confused by the rather
  # esoteric use of Ruby block syntax here - this is just defining some nested
  # routes; e.g. customers have many tasks, so tasks are defined as resources
  # within customers. The longhand equivalent would be:
  #
  #   resources :customers do
  #     resources :tasks
  #   end
  #
  # ...and the Rails 2 equivalent used to be:
  #
  #  map.resources :customers, :has_many => [ :tasks ]

  resources( :customers      ) { resources :tasks                            }
  resources( :projects       ) { resources :tasks                            }
  resources( :control_panels ) { resources :tasks                            }
  resources( :tasks          ) { resources :users; resources :timesheet_rows }
  resources( :timesheets     ) { resources :timesheet_rows                   }

  resources( :users ) do
    resources :tasks
    resources :timesheets

    resources :saved_reports do
      get 'delete', :on => :member

      # This route is rather confusing and was determined by trial and error.
      # The intention is to get a variant of "new" which takes an ID, for the
      # "copy a report" case. The below achieves it (see "rake routes" and
      # look for "saved_reports#new" - it appears twice in different forms).
      # It also creates "user_saved_report_copy_<foo>()" methods.

      get 'new', :to => 'saved_reports#new', :as => 'copy'
    end

    resource :saved_reports_by_task,     :controller => :saved_reports_by_task,     :only => :create
    resource :saved_reports_by_project,  :controller => :saved_reports_by_project,  :only => :create
    resource :saved_reports_by_customer, :controller => :saved_reports_by_customer, :only => :create
    resource :saved_reports_by_user,     :controller => :saved_reports_by_user,     :only => :create
  end

  resources :audits
  resources :reports
  resources :charts
  resource  :task_imports
  resources :trees

  resources :help

  resource  :saved_report_auto_title, :only => :show
  resource  :timesheet_force_commit,  :only => [ :new, :create ]

  # Finally, the normal default rules at lowest priority

  match '/:controller/:action/:id' => '#index'
  match '/:controller/:action/:id.:format' => '#index'
end

app/helpers/reports_helper.rb
########################################################################
# File::    reports_helper.rb
# (C)::     Hipposoft 2008
#
# Purpose:: Support functions for views related to report generation.
#           See controllers/reports_controller.rb for more.
# ----------------------------------------------------------------------
#           18-Feb-2008 (ADH): Created.
########################################################################

module ReportsHelper

  include TrackRecordReport

  # Helper class for ReportYear and reporthelp_week_selection.

  class ReportWeek
    def initialize( year, week )
      @id    = "#{ year }_#{ week }"
      @start = "#{ week } (starts Mon #{ Timesheet.date_for( year, week, TimesheetRow::FIRST_DAY ) })"
      @end   = "#{ week } (ends Sun #{ Timesheet.date_for( year, week, TimesheetRow::LAST_DAY ) })"
      @all   = "#{ week }, Mon #{ Timesheet.date_for( year, week, TimesheetRow::FIRST_DAY ) } - Sun #{ Timesheet.date_for( year, week, TimesheetRow::LAST_DAY ) }"
    end

    attr_reader( :start, :end, :all, :id )
  end

  # Helper class for ReportYear and reporthelp_month_selection.

  class ReportMonth
    def initialize( year, month )
      @id    = "#{ year }_#{ month }"
      @start = "#{ month } (start of #{ Date::MONTHNAMES[ month ] } #{ year })"
      @end   = "#{ month } (end of #{ Date::MONTHNAMES[ month ] } #{ year })"
      @all   = "#{ month }, #{ Date::MONTHNAMES[ month ] } #{ year }"
    end

    attr_reader( :start, :end, :all, :id )
  end

  # Helper class for reporthelp_week_selection and reporthelp_month_selection.
  # Initialize by passing a year for a full set of months, or by passing a
  # year and a range of accurate dates. If the year matches the first or last
  # date in that range, then the months associated with the year will be
  # restricted according to the matching start and/or end date. The range, if
  # given, MUST have a "first" date which is earlier in the year, or at worst
  # the same date as the "last" date (i.e. don't pass in "backwards" ranges).
  #
  # Commercial numbered weeks within which a given date falls may start or end
  # on the previous or next year. If the caller provides a limiting date range
  # that exhibits this (e.g. passes in 31st December 2008, which actually lies
  # in week 1, 2009) then the ReportYear object can do nothing other than
  # represent a full set of its own numbered weeks. If you want to create an
  # object for the extra year, where applicable, you must do so manually.
  #
  class ReportYear
    def initialize( year, date_range = nil )
      @title  = year.to_s
      @weeks  = []
      @months = []

      # "limit" is set if the object is being built for the current year.
      # Weeks and months are checked and any that lie in the future are
      # not included.

      today = Date.current
      limit = ( year == today.year )
      range = ( 1..( Timesheet.get_last_week_number( year ) ) )

      # Work out the weeks, limited as above, or perhaps by an optional date
      # range passed in by the caller.

      range.each do | week |
        first_day_of_week = Timesheet.date_for( year, week, TimesheetRow::FIRST_DAY, true )
        last_day_of_week  = first_day_of_week + 6

        break if (
          ( limit      and first_day_of_week > today           ) or
          ( date_range and first_day_of_week > date_range.last )
        )

        next if (
          ( date_range and last_day_of_week < date_range.first )
        )

        @weeks.unshift( ReportWeek.new( year, week ) )
      end

      # Work out the months, again limited as above.

      ( 1..12 ).each do | month |

        break if (
          ( limit      and month > today.month           ) or
          ( date_range and month > date_range.last.month and date_range.last.year == year )
        )

        next if (
          ( date_range and month < date_range.first.month and date_range.first.year == year  )
        )

        @months.unshift( ReportMonth.new( year, month ) )
      end
    end

    attr_reader( :title, :weeks, :months )
  end

  # Use the Calendar Date Select plug-in to generate a selector for the
  # start time of a report. Pass the form instance upon which to operate.
  #
  def reporthelp_start_time( form )
    return form.calendar_date_select(
      :range_start,
      {
        :embedded   => false,
        :year_range => Timesheet.used_range()
      }
    )
  end

  # Use the Calendar Date Select plug-in to generate a selector for the
  # end time of a report. Pass the form instance upon which to operate.

  def reporthelp_end_time( form )
    return form.calendar_date_select(
      :range_end,
      {
        :embedded   => false,
        :year_range => Timesheet.used_range()
      }
    )
  end

  # Return HTML suitable for inclusion in a form which provides
  # a pull-down menu of years for the full permitted time range
  # subdivided into months. Pass the form being constructed and
  # ":range_month_start" or ":range_month_end".
  #
  def reporthelp_month_selection( form, method )
    start_or_end = ( method == :range_month_start ) ? :start : :end

    form.grouped_collection_select(
      method,
      get_year_array(), # Use years for groups
      :months,          # A years's "months" method returns its month list
      :title,           # Use the year 'title' for the group labels
      :id,              # A month's "id" method returns the value for an option tag
      start_or_end,     # A month's "start" or "end" method is used for the option contents
      {
        :include_blank => '-'
      }
    )
  end

  # Return HTML suitable for inclusion in a form which provides
  # a pull-down menu of years for the full permitted time range
  # subdivided into weeks. Pass the form being constructed and
  # ":range_week_start" or ":range_week_end".
  #
  def reporthelp_week_selection( form, method )
    start_or_end = ( method == :range_week_start ) ? :start : :end

    form.grouped_collection_select(
      method,
      get_year_array(), # Use years for groups
      :weeks,           # A years's "weeks" method returns its week list
      :title,           # Use the year 'title' for the group labels
      :id,              # A week's "id" method returns the value for an option tag
      start_or_end,     # A week's "start" or "end" method is used for the option contents
      {
        :include_blank => '-'
      }
    )
  end

  # Return HTML suitable for inclusion in a form which provides
  # options such as "this month" or "one week ago" in a selection
  # list. Pass the form being constructed and ":range_one_month"
  # or ":range_one_week".
  #
  def reporthelp_one_selection( form, method )
    now = DateTime.now.utc

    if ( method == :range_one_week )
      strings = [
        apphelp_view_hint( :last_week,     SavedReportsController ),
        apphelp_view_hint( :this_week,     SavedReportsController ),
        apphelp_view_hint( :two_weeks_ago, SavedReportsController ),
      ]
      dates = [
        now - 1.week,
        now,
        now - 2.weeks
      ]
      objects = dates.map do | date |
        ReportWeek.new( date.year, date.cweek )
      end
    else
      strings = [
        apphelp_view_hint( :last_month,     SavedReportsController ),
        apphelp_view_hint( :this_month,     SavedReportsController ),
        apphelp_view_hint( :two_months_ago, SavedReportsController ),
      ]
      dates = [
        now - 1.month,
        now,
        now - 2.months
      ]
      objects = dates.map do | date |
        ReportMonth.new( date.year, date.month )
      end
    end

    keys  = [ "last", "this", "two" ]
    array = strings.map.with_index do | string, index |
      o       = OpenStruct.new
      o.value = keys[ index ]
      o.text  = string % objects[ index ].all # The "all" method on a ReportWeek or ReportMonth gives its name/date in a suitable format
      o
    end

    form.collection_select(
      method,
      array,
      :value,
      :text,
      {
        :include_blank => '-'
      }
    )
  end

  # Return HTML suitable for inclusion in the form passed in the
  # first parameter (i.e. the 'f' in "form for ... do |f|" ), which
  # provides a selection list allowing the user to choose a report
  # frequency (weekly, monthly etc.).
  #
  def reporthelp_frequency_selection( form )
    collection = []

    Report.labels.each_index do | index |
      collection.push( [ Report.labels[ index ], index ] )
    end

    form.select( :frequency, collection )
  end

  # Return HTML suitable for inclusion in the form passed in the
  # first parameter (i.e. the 'f' in "form for ... do |f|" ), based
  # on the user array given in the second parameter, which provides:
  #
  # * A <select> tag with options listing all users in the array
  #   in the order in which they are stored in that array.
  #
  # * An empty string if the input users array is itself empty.
  #
  def reporthelp_user_selection( form, users )
    if ( users.empty? )
      return ''
    else
      return apphelp_collection_select(
        form,
        'reportable_user_ids',
        users,
        :id,
        :name
      )
    end
  end

  # Generate a sort field selector menu for the given form which will use
  # the given method to set the chosen option in the report - one of
  # ":customer_sort_field", ":project_sort_field" or ":task_sort_field".
  #
  def reporthelp_sorting_selector( form, method )
    return apphelp_select(
      form,
      method,
      [
        [ 'Sort by name',          'title'      ],
        [ 'Sort by code',          'code'       ],
        [ 'Sort by addition date', 'created_at' ]
      ],
      false
    )
  end

  # Generate a menu for the given form allowing the user to choose a grouping
  # option.
  #
  def reporthelp_grouping_selector( form )
    return apphelp_select(
      form,
      :task_grouping,
      [
        [ 'No special grouping',                'default'  ],

app/views/reports/_comprehensive.html.erb
<%-
# Based on "@report", render a comprehensive per-task, per-user report.
# Only render if the report's "user_details" flag is set.
-%>

<% if ( @report.filtered_tasks.empty? or @report.filtered_users.empty? ) -%>
    <h2 class="report_subtitle">
      Comprehensive report for <%= @report.display_range %>

      <div class="floated_link">
        <%= link_to( 'Alter report', edit_user_saved_report_path( :id => @saved_report.id, :user_id => @saved_report.user_id ) ) %>
      </div>
    </h2>

<%   if ( @report.filtered_users.empty? and not @report.users.empty? ) -%>
    <p>
      None of the selected users booked any hours against the reportable tasks
      within the time range specified.
    <p>
<%   else -%>
    <p>
      Cannot find any tasks or users for this report.
    </p>
<%   end -%>
<% elsif ( @report.user_details ) %>
    <!-- Per-task, per-user fully detailed report -->

    <h2 class="report_subtitle">
      Comprehensive report for <%= @report.display_range %>
      <%= ( @report.filtered_users.empty? ) ? '(all users)' : '(selected users only)' %>

      <div class="floated_link">
        <%= link_to( 'Alter report', edit_user_saved_report_path( :id => @saved_report.id, :user_id => @saved_report.user_id ) ) %>
      </div>
    </h2>

<%   if ( @report.filtered_tasks.empty? ) -%>
    <p>
      No tasks matching your report&rsquo;s specification can be found.
    </p>
<%   elsif ( not @report.has_rows? ) -%>
    <p>
      There are no non-zero totals for rows in the requested report.
    </p>
<%   else -%>
    <p></p>
    <table class="report display_table ts_show_table">

      <!-- Heading - show dates/totals based on report frequency -->

      <tr class="info">
        <th>&nbsp;</th>

<%     @report.each_column_range do | range | -%>
        <th>
          <span title="<%= apphelp_range_plain( range ) %>">
            <%= @report.column_heading( range ) %>
<%       if ( @report.partial_column?( range ) ) -%>
            <br />
            <em>(partial)</em>
<%       end -%>
          </span>
        </th>
<%     end -%>

        <th>Row total</th>
      </tr>

      <!-- Section and task list, date range breakdown -->

<%
       @report.each_row do | row, task |
         section, is_new_section, group, is_new_group = @report.retrieve( task.id.to_s )

         if ( is_new_section )
           row_class = cycle( 'even', 'odd' )
-%>
      <!-- New section -->

      <tr class="<%= row_class %>">
        <th class="ts_show_heading"><%= section.title( self ) %></th>
<%         @report.each_cell_for( section ) do | section_cell | -%>
        <th class="ts_show_heading ts_show_work"><%= reporthelp_hours( section_cell ) %></th>
<%         end -%>
        <th class="ts_show_heading ts_show_work"><%= reporthelp_hours( section, true ) %></th>
      </tr>
<%       elsif ( is_new_group ) -%>
      <!-- New group -->

      <tr class="even group_gap">
        <th colspan="<%= @report.column_count() + 2 %>"></th>
      </tr>

<%       end -%>
      <!-- Task cross-user data -->

<%       row_class = cycle( 'even', 'odd' ) -%>
      <tr class="ts_show_row <%= row_class %>">
        <td class="ts_show_task <%= taskhelp_billable_class( task ) %> <%= taskhelp_active_class( task ) %>">
          <%= apphelp_augmented_link( task ) %>
        </td>

        <!-- Task cross-user breakdown -->

<%       @report.each_cell_for( row ) do | cell | -%>
        <td class="ts_show_work"><%= reporthelp_hours( cell ) %></td>
<%       end -%>

        <!-- Task cross-user total -->

        <th class="ts_show_total total"><%= reporthelp_hours( row, true ) %></th>
      </tr>

      <!-- Task per-user data -->

<%       @report.each_user_on_row( row ) do | user, row_total_for_user | -%>
      <tr class="ts_show_row <%= row_class %>">
        <td class="ts_show_task ts_task_user_detail">
          &nbsp;&mdash;&nbsp;<%= user.name %>
        </td>

        <!-- Task per-user breakdown -->

<%         @report.each_cell_for_user_on_row( user, row ) do | cell_for_user | -%>
        <td class="ts_show_work ts_work_user_detail"><%= reporthelp_hours( cell_for_user ) %></td>
<%         end -%>

        <!-- Task per-user total -->

        <th class="ts_show_total ts_total_user_detail total"><%= reporthelp_hours( row_total_for_user, true ) %></th>
      </tr>
<%       end -%>
<%     end -%>

      <!-- Column totals -->

      <tr class="<%= cycle( 'even', 'odd' ) %>">
        <th class="total">Column total:</th>

<%     @report.each_column_total do | total | -%>
        <td class="total"><%= reporthelp_hours( total, true ) %></td>
<%     end -%>

        <td class="overall_total"><%= reporthelp_hours( @report, true ) %></td>
      </tr>
    </table>

<%   end -%>
<% end -%>

app/views/reports/_export_elements.html.erb
<%
  # Render an 'export as CSV' form for a task. Render with the following local
  # variables:
  #
  #   form_type: Must be ":task", to export the task summary report, ":user",
  #              to export the user summary report - only valid if the report
  #              contains a non-empty user list - or ":comprehensive" for a
  #              per-user, per-task report - also only valid if the report
  #              contains a non-empty user list.

  generators = []

  TrackRecordReportGenerator.submodules.each do | submodule |
    generator = controller.dup.extend( submodule )

    if ( generator.understands?( form_type ) )
      generators << { generator: generator, submodule: submodule }
    end
  end

  unless ( generators.empty? )
-%>
    <br />
    <table class="display_table report_actions">
<%  generators.each do | item |
      submodule = item[ :submodule ]
      generator = item[ :generator ]
      options   = generator.invocation_options_for( form_type ) -%>
      <tr class="display_row <%= cycle( 'odd', 'even' ) %>">
        <td>
          <%= submit_tag( generator.invocation_button_title_for( form_type ) || "Export", :name => "#{ submodule.name.underscore }[#{ form_type }]" ) %>
        </td>
        <td class="wide">
<%    if ( options.nil? || options.empty? ) -%>
          &nbsp;
<%    else -%>
<%      options.each do | option | -%>
          <%= reporthelp_export_option( submodule, option )%><%= option == options.last ? '' : tag( :br ) %>
<%      end -%>
<%    end -%>
        </td>
      </tr>
<%  end -%>
    </table>
<% end -%>

app/views/reports/_tasks.html.erb
<%-
# Based on "@report", render a per-task report.
-%>
    <h2 class="report_subtitle">
      Task data for <%= @report.display_range %>
      <%= ( @report.filtered_users.empty? ) ? '(all users)' : '(selected users only)' %>

      <div class="floated_link">
        <%= link_to( 'Alter report', edit_user_saved_report_path( :id => @saved_report.id, :user_id => @saved_report.user_id ) ) %>
      </div>
    </h2>

<% if ( @report.filtered_tasks.empty? ) -%>
    <p>
      No tasks matching your report&rsquo;s specification can be found.
    </p>
<% elsif ( not @report.has_rows? ) -%>
    <p>
      There are no non-zero totals for rows in the requested report.
    </p>
<% else -%>
    <p></p>
    <table class="report display_table ts_show_table">

      <!-- Heading - show dates/totals based on report frequency -->

      <tr class="info">
        <th>&nbsp;</th>

<%   @report.each_column_range do | range | -%>
        <th>
          <span title="<%= apphelp_range_plain( range ) %>">
            <%= @report.column_heading( range ) %>
<%     if ( @report.partial_column?( range ) ) -%>
            <br />
            <em>(partial)</em>
<%     end -%>
          </span>
        </th>
<%   end -%>

        <th>Row total</th>
<%   if ( @report.filtered_users.empty? ) -%>
        <th>Duration</th>
        <th>Remaining</th>
<%   end -%>
      </tr>

      <!-- Section and task list, date range breakdown -->

<%
     @report.each_row do | row, task |
       section, is_new_section, group, is_new_group = @report.retrieve( task.id.to_s )

       if ( is_new_section )
         row_class = cycle( 'even', 'odd' )
-%>
      <!-- New section -->

      <tr class="<%= row_class %>">
        <th class="ts_show_heading"><%= section.title( self ) %></th>
<%       @report.each_cell_for( section ) do | section_cell | -%>
        <th class="ts_show_heading ts_show_work"><%= reporthelp_hours( section_cell ) %></th>
<%       end -%>
        <th class="ts_show_heading ts_show_work"><%= reporthelp_hours( section, true ) %></th>
<%       if ( @report.filtered_users.empty? ) -%>
        <th class="ts_show_heading ts_show_work">&nbsp;</th>
        <th class="ts_show_heading ts_show_work">&nbsp;</th>
<%       end -%>
      </tr>
<%     elsif ( is_new_group ) -%>
      <!-- New group -->

      <tr class="even group_gap">
        <th colspan="<%= @report.column_count() + 2 %>"></th>
      </tr>

<%     end -%>
      <!-- Task data -->

<%       row_class = cycle( 'even', 'odd' ) -%>
      <tr class="ts_show_row <%= row_class %>">
        <td class="ts_show_task <%= taskhelp_billable_class( task ) %> <%= taskhelp_active_class( task ) %>">
          <%= apphelp_augmented_link( task ) %>
        </td>

        <!-- Task breakdown -->

<%     @report.each_cell_for( row ) do | cell | -%>
        <td class="ts_show_work"><%= reporthelp_hours( cell ) %></td>
<%     end -%>

        <!-- Task total -->

        <th class="ts_show_total total"><%= reporthelp_hours( row, true ) %></th>
<%     if ( @report.filtered_users.empty? ) -%>
<%       if ( task.duration == 0.0 ) -%>
        <td class="ts_show_work">&nbsp;</td>
        <td class="ts_show_work">&nbsp;</td>
<%        else -%>
        <td class="ts_show_work"><%= apphelp_terse_hours( task.duration ) %></td>
        <td class="ts_show_work">
          <%= reporthelp_decorated_hours( task.duration - ( row.try( :committed ) || 0 ),
                                          task.duration - ( row.try( :total     ) || 0 ) ) %>
        </td>
<%       end -%>
<%     end -%>

      </tr>
<%   end -%>

      <!-- Column totals -->

      <tr class="<%= cycle( 'even', 'odd' ) %>">
        <th class="total">Column total:</th>

<%     @report.each_column_total do | total | -%>
        <td class="total"><%= reporthelp_hours( total, true ) %></td>
<%     end -%>

        <td class="overall_total"><%= reporthelp_hours( @report, true ) %></td>
<%   if ( @report.filtered_users.empty? ) -%>
        <td class="total">
          <%= apphelp_terse_hours( @report.total_duration, true ) %>
        </td>
        <td class="total">
<%     if ( @report.total_actual_remaining.nil? ) -%>
          &nbsp;
<%     else -%>
          <%= reporthelp_decorated_hours( @report.total_actual_remaining, @report.total_potential_remaining ) %>
<%     end -%>
        </td>
<%   end -%>
      </tr>
    </table>

<% end -%>

app/views/reports/_users.html.erb
<%-
# Based on "@report", render a user summary report. Only render if the
# report's "users" array is not empty, indicating that a selection of
# users has been made.
-%>
<% if ( @report.filtered_tasks.empty? or @report.filtered_users.empty? ) -%>
    <h2 class="report_subtitle">User summaries for <%= @report.display_range %></h2>
<%   if ( @report.filtered_users.empty? and not @report.users.empty? ) -%>
    <p>
      None of the selected users booked any hours against the reportable tasks
      within the time range specified.
    <p>
<%   else -%>
    <p>
      Cannot find any tasks or users for this report.
    </p>
<%   end -%>
<% else %>
    <!-- Per-user summaries -->

    <h2 class="report_subtitle">
      User summaries for <%= @report.display_range %>
      <div class="floated_link">
        <%= link_to( 'Alter report', edit_user_saved_report_path( :id => @saved_report.id, :user_id => @saved_report.user_id ) ) %>
      </div>
    </h2>

    <p></p>
    <table class="report display_table ts_show_table">

      <!-- Heading - show user names -->

      <tr class="info">
        <th class="total">Name:</th>

<%   @report.each_user do | user | -%>
        <th><%= h( user.name ) %></th>
<%   end -%>

        <th>Row total</th>
      </tr>

      <!-- Section and task list, user breakdown -->

<%   @report.each_row do | row, task |
       section, is_new_section, group, is_new_group = @report.retrieve( task.id.to_s )

       if ( is_new_section )
         row_class = cycle( 'even', 'odd' ) -%>
      <!-- New section -->

      <tr class="<%= row_class %>">
        <th class="ts_show_heading"><%= section.title( self ) %></th>
<%       @report.each_user do | user | -%>
        <th class="ts_show_heading ts_show_work"><%= reporthelp_hours( section.try( :user_total, user.id.to_s ) ) %></th>
<%       end -%>
        <th class="ts_show_heading ts_show_work"><%= reporthelp_hours( section, true ) %></th>
      </tr>
<%     elsif ( is_new_group ) -%>
      <!-- New group -->

      <tr class="even group_gap">
        <th colspan="<%= @report.user_count() + 2 %>"></th>
      </tr>

<%     end -%>
      <!-- Task data -->

      <tr class="ts_show_row <%= cycle( 'even', 'odd' ) %>">
        <td class="ts_show_task <%= taskhelp_billable_class( task ) %> <%= taskhelp_active_class( task ) %>"><%= h( task.title ) %></td>

        <!-- Per-user breakdown -->

<%     @report.each_user do | user | -%>
        <td class="ts_show_work"><%= reporthelp_hours( row.try( :user_total, user.id.to_s ) ) %></td>
<%     end -%>

        <!-- Task total -->

        <th class="ts_show_total total"><%= reporthelp_hours( row, true ) %></th>
      </tr>
<%   end -%>

      <!-- Column totals -->

      <tr class="<%= cycle( 'even', 'odd' ) %>">
        <th class="total">Column total:</th>

<%   @report.each_user do | user | -%>
        <td class="total"><%= reporthelp_hours( @report.try( :user_total, user.id.to_s ), true ) %></td>
<%   end -%>

        <td class="overall_total"><%= reporthelp_hours( @report, true ) %></td>
      </tr>
    </table>

<% end -%>

app/views/reports/show.html.erb
    <h1><%= @report.label %> report<%= @report.title.empty? ? '' : " \"#{ h( @report.title ) }\"" %></h1>

    <p>
      <%= taskhelp_billable_help %> <%= taskhelp_active_help %>
    </p>

    <%= form_for( :report, { :url => { :action => 'show' }, :method => :get } ) do | f | %><%= hidden_field_tag( :generator, "1" ) %>

<% if ( @report.user_details ) -%> 
<%= render :partial => 'comprehensive' %>
<%= render( { :partial => 'export_elements', :locals  => { :form_type => :comprehensive } } ) %>
<% end -%>
<%= render :partial => 'tasks' %>
<%= render( { :partial => 'export_elements', :locals  => { :form_type => :task } } ) %>
<% unless ( @report.users.empty? ) -%>
<%= render :partial => 'users' %>
<%= render( { :partial => 'export_elements', :locals  => { :form_type => :user } } ) %>
<% end -%>

<%= "    " %><% end %>

    <!-- Form to modify report, make new report, cancel -->

    <br />
    <br />
    <div class="centred">
      <%= link_to( 'Alter report', edit_user_saved_report_path( :id => @saved_report.id, :user_id => @saved_report.user_id ) ) %>,
      <%= link_to( 'create a new report', new_user_saved_report_path( :user_id => @saved_report.user_id ) ) %> or
      <%= link_to( 'cancel', home_path() ) %>.

<% if ( @saved_report.shared? ) -%>
      <br />
      <br />
      The share URI for this report is:
      <%= link_to( report_url(), report_path() ) %>
<% else -%>
      This report is not shared.
<% end -%>
    </div>